--- # ------------------------------------------------------------------------------------------- ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: gokv-config
  labels:
    {{- include "gokv.labels" . | nindent 4 }}    
  annotations:
    {{- include "gokv.defaultAnnotations" . | nindent 4 }}
data:
  gokv.yaml: {{- .Values.gokv.yaml | toYaml | indent 1 }}