--- # ------------------------------------------------------------------------------------------- ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-gokv
  labels:
    {{- include "gokv.labels" . | nindent 4 }}    
  annotations:
    {{- include "gokv.defaultAnnotations" . | nindent 4 }}
automountServiceAccountToken: true