--- # ------------------------------------------------------------------------------------------- Service-ws
apiVersion: v1
kind: Service
metadata:
  name: gokv-ws
  labels:
    {{- include "gokv.labels" . | nindent 4 }}    
  annotations:
    {{- include "gokv.defaultAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: ws
      port: 5334
      protocol: TCP
      targetPort: 5334
  selector:
    {{- include "gokv.selectorLabels" . | nindent 4 }}
    {{- with .Values.pod.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
--- # ------------------------------------------------------------------------------------------- Service-http
apiVersion: v1
kind: Service
metadata:
  name: gokv
  labels:
    {{- include "gokv.labels" . | nindent 4 }}    
  annotations:
    {{- include "gokv.defaultAnnotations" . | nindent 4 }}
spec:
  {{- if .Values.service.http.nodeport }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      {{- with .Values.service.http.nodeport }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "gokv.selectorLabels" . | nindent 4 }}
    {{- with .Values.pod.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}