--- # ------------------------------------------------------------------------------------------- StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gokv
  labels:
    {{- include "gokv.labels" . | nindent 4 }}    
  annotations:
    {{- include "gokv.defaultAnnotations" . | nindent 4 }}
spec:
  replicas: {{ default 3 .Values.service.replicas }}
  revisionHistoryLimit: 3
  minReadySeconds: 10
  serviceName: gokv-gossip
  selector:
    matchLabels:
      {{- include "gokv.selectorLabels" . | nindent 6 }}    
  template:
    metadata:
      annotations:
        {{- include "gokv.defaultAnnotations" . | nindent 8 }}
        {{- with .Values.pod.annotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "gokv.selectorLabels" . | nindent 8 }}    
        {{- with .Values.pod.labels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- with .Values.pod.affinity }}
      affinity:
        {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{ . | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: sa-gokv
      {{- if .Values.gokv.yaml }}
      volumes:
        - name: config
          configMap:
            name: gokv-config
      {{- end }}
      containers:
        - name: gokv
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          ports:
            - name: gossip
              containerPort: 5334
            - name: http
              containerPort: 80
          {{- with .Values.pod.nodeSelector }}
          resources:
            {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.gokv.yaml }}
          volumeMounts:
            - name: config
              mountPath: /opt/gokv/cfg
          {{- end }}
          startupProbe:
            httpGet:
              path: /healthz/live
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3