--- # ------------------------------------------------------------------------------------------- StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gokv
spec:
  selector:
    matchLabels:
      app: gokv
  serviceName: "gokv-headless"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: gokv
    spec:
      containers:
      - name: gokv
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: gossip
          containerPort: {{ .Values.service.gossipPortTCP }}
        volumeMounts:
        - name: config
          mountPath: /opt/gokv
      volumes:
        - name: config
          configMap:
            name: gokv-config