# this section contains global configs for the application
global:
  # this key is a list of possible imagePullSecrets, if required
  imagePullSecrets: []


# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  # Set the repository, which is used to receive the image.
  repository: ghcr.io/jnnkrdb/gokv
  
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  
  # This sets the pull policy for images.
  pullPolicy: Always

# This section builds out the deployed pod
pod:
  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  annotations: {}
  
  # This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  labels: {}

  # Set required pod affinities or antiaffinities.
  affinity: {}

  # Set required pod tolerations.
  tolerations: []
  
  # Set required pod nodeSelector labels.
  nodeSelector: {}

  # Set the resources which can be used per pod.
  resources: {}

# This section sets the default service configs.
service:
  
  # Set the tcp port which is used to listen for gossip.
  gossipPortTCP: 3453

  # Set the http port for http connections.
  httpPortTCP: 80

# this section contains the content of the gokv.yaml as raw string in vaml format. will be deployed as configmap
gokv:
  # This is the content of the yaml file. If its empty, then the default will be used.
  yaml: |-
    this: ""
    isSoWrong: true
