name: RUNNING GO TESTS

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'gokv/**'
  pull_request:
    branches: 
      - master 
      - dev
    paths:
      - 'gokv/**'

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      
      - name: Change Dir
        run: cd ./gokv

      - name: Install Deps
        run: go mod download

      - name: Test [./gokv/...]
        run: go test ./gokv/... -v